### ISSUE TITLE
:setlocal ts=8 nolist

### ISSUE THREAD

**Issue by justinmk** [int3/vim-extradite#35]
The layout uses tabs, so it should `:setlocal ts=8 nolist` in the extradite buffer.

**Comment by xaizek** [comment]
Added `nolist`, but not `ts=8` as `ts=1` is already there which is probably on purpose. I tried it on a file which has contributors with names of different length and `ts=8` actually creates even less consistent mess, which is quite hard to read.

As far as I can tell tabulation character is used just to highlight author names properly (as they can contain spaces), and not to align columns.
